.Dd December 1, 2024
.Dt БЕРЕТВРОТ.РФ 7
.Os Берем в рот
.
.Sh NAME
.Nm беретврот.рф
.Nd место, где все берут в рот.
.
.Sh SYNOPSIS
.Nm Молодцы
сосут концы
.
.Sh DESCRIPTION
На этом сайте можно
увидеть людей,
которые любят
брать у кого-то в рот.
Это стоит уважать,
ведь каждый может дать в рот,
но не каждый -
взять.
.
.Pp
Под этим доменом
можно увидеть людей,
которые всегда
готовы и рады
взять в рот.
Не стоит проходить мимо
таких великих людей,
а также необходимо
.Lk https://главная.беретврот.рф знать своих героев
в лицо.
.
.
.Pp
Итак,
дальше пойдет
список добродетелей,
которых не стыдно
упомянуть здесь,
ведь они сделали
влиятельный вклад
в брании в рот:
.Bl -bullet
.It
.Lk https://наки.беретврот.рф Накидай ,
по совместительству владеет доменом
.It
.Lk https://эндкул.беретврот.рф/ Эндкул ,
по совместительству хостит пользовательские страницы
.It
.Lk https://гимура.беретврот.рф Гимура
.It
.Lk https://свифтин.беретврот.рф Свифтин
.It
.Lk https://йорися.беретврот.рф Йорися
.El
.
.Ss Своя страница
Вы хотели бы
взять в рот,
но чего-то
боитесь?
Не беда!
Чтобы получить
собственную страницу,
надо всего-лишь
перейти
на интересующий домен
(например,
.Ql сульфур.беретврот.рф ) ,
и, если он
не был занят,
то у вас появится форма
для его создания.
.
.Sh SEE ALSO
.Bl -bullet
.It
.Lk https://главная.беретврот.рф Навигатор с возможностью выбора случайного домена
.It
.Lk https://github.com/6epeMBPoT Огранизация на Github
.El
.
.Sh AUTHORS
В рот берет
каждый
по-своему.
.
.Sh BUGS
Если у вас
возникли какие-то вопросы
или идеи,
то не стесняйтесь
брать в рот,
или же можно
открыть
.Lk https://github.com/orgs/6epeMBPoT/discussions/new/choose дискуссию
по интересующей теме
на Github.
